import { useState } from 'react';
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownLeft, ArrowUpRight, Landmark, PiggyBank, Settings2, ShieldCheck, Wallet } from 'lucide-react';
import { ACCOUNTS, CONFIG, EXPENSES } from './config';
import { usePlanner } from './context';
import { accountBalances, getBalanceAlert, money, monthlySummary, number, shortDate, totalBalance, uid } from './lib';
import { AddButton, Amount, EditActions, Empty, Field, Form, Modal, num, Panel, Progress, str } from './components';
import type { AccountId, MonthRecord } from './types';

export default function Finance() {
  const { data, setData, today, notify } = usePlanner();
  const [editing, setEditing] = useState<Partial<MonthRecord> | null>(null);
  const [editSavings, setEditSavings] = useState(false);
  const [editAccounts, setEditAccounts] = useState(false);
  const [selectedMonth, setSelectedMonth] = useState(today.slice(0, 7));
  const [error, setError] = useState('');
  const balances = accountBalances(data, today);
  const balance = totalBalance(data, today);
  const summaries = monthlySummary(data);
  const selected = summaries.find(r => r.month === selectedMonth);
  const alert = getBalanceAlert(balance, today, data.settings.graduationDate, totalBalance(data, CONFIG.finance.checkpointDate));
  const chartData = [{ month: '初始', balance: Object.values(data.settings.initialBalances).reduce((a, b) => a + b, 0) }, ...summaries.filter(s => s.month <= today.slice(0, 7)).map(s => ({ month: s.month, balance: s.balance }))];
  const savingsGoals = [
    { key: 'emergency', name: '应急储备', target: data.settings.monthlyLivingCost * CONFIG.finance.emergencyMonths, icon: ShieldCheck, note: `${CONFIG.finance.emergencyMonths} 个月生活费` },
    { key: 'french', name: '法语考试', target: CONFIG.finance.frenchTarget, icon: LanguagesIcon, note: 'TEF Canada 备考与考试' },
    { key: 'pr', name: 'PR 申请费', target: CONFIG.finance.prTarget, icon: Landmark, note: '为递交申请提前准备' },
  ] as const;
  function save(form: FormData) {
    const record: MonthRecord = { id: editing?.id ?? uid(), month: str(form, 'month'), account: str(form, 'account') as AccountId, partTime: num(form, 'partTime'), fullTime: num(form, 'fullTime'), expenses: { rent: num(form, 'rent'), food: num(form, 'food'), phone: num(form, 'phone'), transport: num(form, 'transport'), other: num(form, 'other') }, note: str(form, 'note') };
    if (data.months.some(r => r.id !== record.id && r.month === record.month && r.account === record.account)) { setError('该账户在这个月已有记录，请编辑已有记录，或选择其他账户。'); return; }
    setData(d => ({ ...d, months: editing?.id ? d.months.map(r => r.id === record.id ? record : r) : [...d.months, record] }));
    setSelectedMonth(record.month); setEditing(null); notify('月度收支已保存，余额已更新');
  }
  return <><div className="page-title"><div><div className="eyebrow">为每一个阶段留好余地</div><h1>财务规划<span className="heading-dot">.</span></h1><p>照顾好现在，也为下一阶段留好余地。金额均为加元。</p></div><AddButton onClick={() => { setError(''); setEditing({ month: selectedMonth, account: 'living' }); }}>记录收支</AddButton></div>
    <section className="finance-summary panel"><div><span className="muted small">当前总余额</span><div className="finance-balance">{money(balance)}<span>CAD</span></div><span className={`badge ${alert.level}`}>{alert.title}</span></div><div className="graduation-saving"><div className="flex-between"><span>毕业时目标余额</span><strong>{money(CONFIG.finance.graduationTarget)}</strong></div><Progress value={Math.max(0, balance)} max={CONFIG.finance.graduationTarget} label="毕业储备目标" /><p>{balance >= CONFIG.finance.graduationTarget ? `高于目标 ${money(balance - CONFIG.finance.graduationTarget)}` : `距离目标还差 ${money(CONFIG.finance.graduationTarget - balance)}`}<span>{shortDate(data.settings.graduationDate)}</span></p></div></section>
    {alert.level !== 'green' && <div className={`notice ${alert.level}`} role="alert"><Wallet size={19} /><div><strong>{alert.title}</strong><p>{alert.detail}</p></div></div>}
    <div className="section-label"><h2>我的三个账户</h2><button className="text-button" onClick={() => setEditAccounts(true)}><Settings2 size={15} />调整初始金额</button></div><div className="account-grid">{ACCOUNTS.map((account, i) => <section className="panel account-card" key={account.id}><div className="flex-between"><span className="account-icon">{i === 0 ? <ShieldCheck size={20} /> : i === 1 ? <Landmark size={20} /> : <Wallet size={20} />}</span><span className="eyebrow">账户 0{i + 1}</span></div><h3>{account.name}</h3><div className={`account-amount ${balances[account.id] < 0 ? 'danger-text' : ''}`}>{money(balances[account.id])}</div><p>{account.description}</p></section>)}</div>
    <div className="finance-columns"><Panel title="余额的变化" action={<span className="small muted">截至 {today.slice(0, 7)}</span>}><div className="balance-chart" role="img" aria-label="月末余额折线图，详细金额见下方月度账本"><ResponsiveContainer width="100%" height="100%" minWidth={0}><LineChart data={chartData} margin={{ top: 12, right: 10, left: -12, bottom: 5 }}><CartesianGrid stroke="var(--line)" vertical={false} strokeDasharray="3 4" /><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fill: 'var(--muted)', fontSize: 12 }} tickFormatter={v => v === '初始' ? v : v.slice(2).replace('-', '.')} dy={8} /><YAxis tickLine={false} axisLine={false} tick={{ fill: 'var(--muted)', fontSize: 12 }} tickFormatter={v => `${v / 1000}k`} /><Tooltip formatter={v => [money(Number(v)), '余额']} contentStyle={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: 8, color: 'var(--text)', fontSize: 13 }} /><ReferenceLine y={CONFIG.finance.graduationTarget} stroke="var(--muted)" strokeDasharray="4 5" /><Line type="monotone" dataKey="balance" stroke="var(--primary)" strokeWidth={2.5} dot={{ fill: 'var(--surface)', strokeWidth: 2, r: 4 }} activeDot={{ r: 6 }} /></LineChart></ResponsiveContainer></div><div className="chart-legend"><span><i />月末余额</span><span><i className="dashed" />毕业目标 {money(CONFIG.finance.graduationTarget)}</span></div>{summaries.length === 0 && <p className="small muted">目前只有初始余额。添加月度收支后，趋势会自动延伸。</p>}</Panel>
    <Panel title="本月支出预算" action={<input className="month-picker" aria-label="查看预算月份" type="month" value={selectedMonth} max={today.slice(0, 7)} onChange={e => { if (e.target.value) setSelectedMonth(e.target.value); }} />}><p className="small muted budget-description">不含房租 · 跨账户合计</p><div className="budget-list">{Object.entries(CONFIG.finance.expenseLimits).map(([key, limit]) => { const spent = selected?.expenses[key as keyof typeof CONFIG.finance.expenseLimits] ?? 0; const over = spent > limit; return <div key={key} className={over ? 'budget-item over' : 'budget-item'}><div className="flex-between"><span>{EXPENSES.find(e => e.key === key)?.label}</span><span><strong>{number(spent)}</strong> / {limit}</span></div><Progress value={spent} max={limit} label={`${key}支出预算`} />{over && <small>超出 {money(spent - limit)}</small>}</div>; })}</div></Panel></div>
    <Panel title="月度账本" action={<span className="small muted">收入 − 支出 = 当月净变化</span>} className="ledger-panel">{!summaries.length ? <Empty icon={<Wallet size={30} />}>还没有收支记录，从这个月开始吧。</Empty> : <div className="month-ledger">{[...summaries].reverse().map(summary => <details className="ledger-month" key={summary.month} open={summary.month === selectedMonth}><summary><span className="ledger-month-name">{summary.month.replace('-', ' 年 ')} 月</span><span><ArrowDownLeft size={14} />收入 <b>{money(summary.income)}</b></span><span><ArrowUpRight size={14} />支出 <b>{money(summary.expense)}</b></span><span>月末余额 <b>{money(summary.balance)}</b></span></summary><div className="table-scroll"><table><thead><tr><th>账户</th><th>兼职</th><th>全职</th>{EXPENSES.map(e => <th key={e.key}>{e.label}</th>)}<th>操作</th></tr></thead><tbody>{summary.rows.map(row => <tr key={row.id}><td>{ACCOUNTS.find(a => a.id === row.account)?.name}{row.note && <small className="cell-note">{row.note}</small>}</td><td>{number(row.partTime)}</td><td>{number(row.fullTime)}</td>{EXPENSES.map(e => <td key={e.key}>{number(row.expenses[e.key])}</td>)}<td><EditActions name={`${row.month}收支`} onEdit={() => { setError(''); setEditing(row); }} onDelete={() => { if (confirm('删除这条收支记录？相关账户与月末余额会重新计算。')) setData(d => ({ ...d, months: d.months.filter(r => r.id !== row.id) })); }} /></td></tr>)}</tbody></table></div></details>)}</div>}</Panel>
    <Panel title="毕业后的专项储蓄" action={<button className="text-button" onClick={() => setEditSavings(true)}>更新储蓄<Settings2 size={15} /></button>}><p className="small muted savings-note">这是已划定用途的资金，不会重复计入总余额。</p><div className="savings-grid">{savingsGoals.map(goal => <div key={goal.key} className="saving-item"><goal.icon size={22} /><h3>{goal.name}</h3><p>{goal.note}</p><div className="flex-between"><strong>{money(data.savings[goal.key])}</strong><span className="small muted">/ {money(goal.target)}</span></div><Progress value={data.savings[goal.key]} max={goal.target} label={`${goal.name}储蓄进度`} />{goal.target === 0 && <small className="muted">请先设置每月生活费</small>}</div>)}</div></Panel>
    <details className="rules-panel"><summary>余额预警规则</summary><ul><li>{CONFIG.finance.checkpointDate} 检查点余额低于 {money(CONFIG.finance.checkpointMinimum)}：黄色提醒，持续至毕业。</li><li>毕业前当前余额低于 {money(CONFIG.finance.preGraduationRed)}：红色紧急模式。</li><li>任何时候当前余额低于 {money(CONFIG.finance.critical)}：最高级预警，优先显示。</li><li>毕业当天目标 {money(CONFIG.finance.graduationTarget)}；未达到时显示黄色提醒。</li></ul><p>月末余额 = 三个账户初始金额合计 + 截至该月的净收支；未记录的月份不会推算支出。检查点使用截至该月的已录入数据。</p></details>
    {editing && <Modal title={editing.id ? '编辑月度收支' : '记录月度收支'} onClose={() => setEditing(null)} wide><Form onSubmit={save} onCancel={() => setEditing(null)}><div className="form-grid"><Field label="月份"><input name="month" type="month" required max={today.slice(0, 7)} defaultValue={editing.month} /></Field><Field label="所属账户" hint="本条收入与支出均记入此账户"><select name="account" defaultValue={editing.account}>{ACCOUNTS.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="兼职收入（CAD）"><Amount name="partTime" value={editing.partTime} /></Field><Field label="全职收入（CAD）"><Amount name="fullTime" value={editing.fullTime} /></Field>{EXPENSES.map(e => <Field key={e.key} label={`${e.label}支出（CAD）`}><Amount name={e.key} value={editing.expenses?.[e.key]} /></Field>)}<div className="full"><Field label="备注"><input name="note" maxLength={1000} defaultValue={editing.note ?? ''} placeholder="可选，记录这月的特殊支出" /></Field></div></div><p className="form-hint">每个账户每月一条记录；其他账户的收支可另外添加，预算会自动合计。</p>{error && <p className="form-error" role="alert">{error}</p>}</Form></Modal>}
    {editAccounts && <Modal title="账户初始金额" onClose={() => setEditAccounts(false)}><Form onCancel={() => setEditAccounts(false)} onSubmit={form => { setData(d => ({ ...d, settings: { ...d.settings, initialBalances: { reserve: num(form, 'reserve'), fixed: num(form, 'fixed'), living: num(form, 'living') } } })); setEditAccounts(false); notify('账户初始金额已更新'); }}><p className="form-hint">更改初始金额会重新计算所有历史余额，不会添加收入记录。</p><div className="form-stack">{ACCOUNTS.map(a => <Field key={a.id} label={`${a.name}（CAD）`}><Amount name={a.id} value={data.settings.initialBalances[a.id]} /></Field>)}</div></Form></Modal>}
    {editSavings && <Modal title="更新专项储蓄" onClose={() => setEditSavings(false)}><Form onCancel={() => setEditSavings(false)} onSubmit={form => { const savings = { emergency: num(form, 'emergency'), french: num(form, 'french'), pr: num(form, 'pr') }; setData(d => ({ ...d, savings, settings: { ...d.settings, monthlyLivingCost: num(form, 'monthlyLivingCost') } })); setEditSavings(false); notify('专项储蓄进度已更新'); }}><div className="form-grid"><Field label="每月生活费估算（含房租）"><Amount name="monthlyLivingCost" value={data.settings.monthlyLivingCost} /></Field>{savingsGoals.map(goal => <Field key={goal.key} label={`${goal.name}已存（CAD）`}><Amount name={goal.key} value={data.savings[goal.key]} /></Field>)}</div><p className="form-hint">这些金额只标记用途，不增减账户余额，请按实际预留金额填写。</p></Form></Modal>}
  </>;
}
function LanguagesIcon({ size }: { size: number }) { return <PiggyBank size={size} />; }
