import { useState } from 'react';
import { BriefcaseBusiness, CheckCircle2, Clock3, ExternalLink, Settings2, Users } from 'lucide-react';
import { CONFIG, JOB_STATUSES } from './config';
import { usePlanner } from './context';
import { addDays, daysBetween, inWeek, number, shortDate, uid, weekStart, workProgress } from './lib';
import { AddButton, Amount, EditActions, Empty, Field, Form, Modal, num, Panel, Progress, str } from './components';
import type { Application, Contact, WorkLog } from './types';

export default function Jobs() {
  const { data, setData, today, notify } = usePlanner();
  const [editing, setEditing] = useState<Partial<Application> | null>(null);
  const [contactEditing, setContactEditing] = useState<Partial<Contact> | null>(null);
  const [workEditing, setWorkEditing] = useState<Partial<WorkLog> | null>(null);
  const [employmentOpen, setEmploymentOpen] = useState(false);
  const [teer, setTeer] = useState(0);
  const [error, setError] = useState('');
  const applications = data.applications.filter(a => a.custom && inWeek(a.date, today)).length;
  const contacts = new Set(data.contacts.filter(c => inWeek(c.date, today)).map(c => c.name.trim().toLocaleLowerCase())).size;
  const work = workProgress(data, today);
  function editApplication(application: Partial<Application>) { setTeer(application.teer ?? 0); setError(''); setEditing(application); }
  return <><div className="page-title"><div><div className="eyebrow">走向下一份机会</div><h1>求职与工作<span className="heading-dot">.</span></h1><p>记录每一次尝试，让工作经验有迹可循。</p></div><AddButton onClick={() => editApplication({ date: today, status: 'applied', custom: true })}>添加申请</AddButton></div>
    <div className="jobs-goals"><Panel title="本周定制申请" action={<BriefcaseBusiness size={20} />}><div className="goal-value">{applications}<span>/ {CONFIG.jobs.weeklyApplications} 份</span></div><Progress value={applications} max={CONFIG.jobs.weeklyApplications} label="本周定制申请完成情况" /><p className="small muted">{shortDate(weekStart(today))} — {shortDate(addDays(weekStart(today), 6))}</p></Panel><Panel title="联系行业人士" action={<Users size={20} />}><div className="goal-value">{contacts}<span>/ {CONFIG.jobs.weeklyContacts} 位</span></div><Progress value={contacts} max={CONFIG.jobs.weeklyContacts} label="本周行业联系完成情况" /><button className="text-button" onClick={() => { setError(''); setContactEditing({ date: today }); }}>记录一次联系<Users size={14} /></button></Panel><Panel title="我的申请进展"><div className="pipeline-counts">{JOB_STATUSES.map(status => <div key={status.value}><strong>{data.applications.filter(a => a.status === status.value).length}</strong><span>{status.label}</span></div>)}</div><p className="small muted">共 {data.applications.length} 份申请</p></Panel></div>
    <Panel title="申请记录" action={<span className="small muted">按投递日期排序</span>}>{!data.applications.length ? <Empty icon={<BriefcaseBusiness size={32} />} action={<button className="button" onClick={() => editApplication({ date: today, custom: true, status: 'applied' })}>记录第一份申请</button>}>从一份认真准备的申请开始。</Empty> : <div className="table-scroll"><table className="applications-table"><thead><tr><th>公司 / 职位</th><th>城市</th><th>NOC / TEER</th><th>投递日期</th><th>状态</th><th>备注</th><th>操作</th></tr></thead><tbody>{[...data.applications].sort((a, b) => b.date.localeCompare(a.date)).map(app => <tr key={app.id}><td><strong>{app.company}</strong><small className="cell-note">{app.position}</small>{app.custom && <span className="badge">定制申请</span>}</td><td>{app.city || '—'}</td><td>{app.noc || '未填写'}<small className="cell-note">TEER {app.teer}</small>{app.teer > CONFIG.jobs.highestSkilledTeer && <span className="teer-warning">这类工作不算技术类经验</span>}</td><td>{shortDate(app.date)}</td><td><span className={`badge ${app.status}`}>{JOB_STATUSES.find(s => s.value === app.status)?.label}</span></td><td className="wrap-cell">{app.note || '—'}</td><td><EditActions name={`${app.company}申请`} onEdit={() => editApplication(app)} onDelete={() => { if (confirm(`删除「${app.company}」的申请记录？`)) setData(d => ({ ...d, applications: d.applications.filter(a => a.id !== app.id) })); }} /></td></tr>)}</tbody></table></div>}</Panel>
    <Panel title="技术类工作经验" action={<button className="text-button" onClick={() => setEmploymentOpen(true)}><Settings2 size={15} />入职日期</button>}><div className="work-overview"><div><span className="small muted">可计入累计工时</span><div className="work-hours">{number(work.hours)}<span>/ {CONFIG.jobs.requiredHours} 小时</span></div><Progress value={work.hours} max={CONFIG.jobs.requiredHours} label="技术类工作累计工时" /><p className="small muted">符合记录条件的实际工时 {number(work.rawHours)} 小时；每周最多计入 {CONFIG.jobs.weeklyHourCap} 小时。</p></div><div className="work-date"><Clock3 size={23} /><span>入职满 {CONFIG.jobs.requiredMonths} 个月</span><strong>{work.anniversary ? shortDate(work.anniversary) : '等待设置入职日期'}</strong><small>{work.anniversary ? daysBetween(today, work.anniversary) > 0 ? `还有 ${daysBetween(today, work.anniversary)} 天` : '入职时长已满一年，请同时核对工时' : '设置后自动计算预计日期'}</small></div></div>{work.completed && <div className="notice green"><CheckCircle2 size={21} /><div><strong>满12个月技术类经验</strong><p>已记录满 {CONFIG.jobs.requiredHours} 个可计入小时，且距离入职已满一年。</p></div></div>}{work.hours >= CONFIG.jobs.requiredHours && !work.completed && <p className="notice yellow">已达到工时目标，尚未满足入职满 {CONFIG.jobs.requiredMonths} 个月的时间条件。</p>}<div className="work-actions"><button className="button primary" onClick={() => { if (!data.settings.employmentDate) { setEmploymentOpen(true); return; } setError(''); setWorkEditing({ week: weekStart(today), eligible: false, teer: 0 }); }}><Clock3 size={17} />记录每周工时</button><a className="text-button" href={CONFIG.links.experience} target="_blank" rel="noreferrer">查看 IRCC 经验要求<ExternalLink size={13} /></a></div><p className="form-hint">仅计入你确认符合条件的 TEER 0–3 工时。全日制在读期间、自雇、无薪或未经授权的工作不计入此 CEC 追踪；近 {CONFIG.jobs.lookbackYears} 年以外的周记录不计入。此页用于个人核对，资格需结合官方完整条件确认。</p>
    {data.workLogs.length > 0 && <div className="table-scroll"><table><thead><tr><th>所在周（周一）</th><th>实际工时</th><th>TEER</th><th>符合条件</th><th>备注</th><th>操作</th></tr></thead><tbody>{[...data.workLogs].sort((a, b) => b.week.localeCompare(a.week)).map(log => <tr key={log.id}><td>{shortDate(log.week)}</td><td>{number(log.hours)} 小时</td><td>{log.teer}</td><td><span className={`badge ${log.eligible && log.teer <= CONFIG.jobs.highestSkilledTeer ? 'green' : 'yellow'}`}>{log.teer > CONFIG.jobs.highestSkilledTeer ? 'TEER 不符合' : log.eligible ? '已确认' : '未确认'}</span></td><td className="wrap-cell">{log.note || '—'}</td><td><EditActions name={`${log.week}工时`} onEdit={() => { setError(''); setWorkEditing(log); }} onDelete={() => { if (confirm('删除这周的工时记录？')) setData(d => ({ ...d, workLogs: d.workLogs.filter(l => l.id !== log.id) })); }} /></td></tr>)}</tbody></table></div>}</Panel>
    <Panel title="行业联系记录" action={<button className="text-button" onClick={() => { setError(''); setContactEditing({ date: today }); }}>添加联系<Users size={15} /></button>}>{!data.contacts.length ? <Empty icon={<Users size={28} />}>记下一次交流，也为下一次联系留个线索。</Empty> : <div className="table-scroll"><table><thead><tr><th>日期</th><th>联系人</th><th>交流记录</th><th>操作</th></tr></thead><tbody>{[...data.contacts].sort((a, b) => b.date.localeCompare(a.date)).map(c => <tr key={c.id}><td>{shortDate(c.date)}</td><td>{c.name}</td><td className="wrap-cell">{c.note || '—'}</td><td><EditActions name={`${c.name}联系`} onEdit={() => { setError(''); setContactEditing(c); }} onDelete={() => { if (confirm('删除这条联系记录？')) setData(d => ({ ...d, contacts: d.contacts.filter(row => row.id !== c.id) })); }} /></td></tr>)}</tbody></table></div>}</Panel>
    {editing && <Modal title={editing.id ? '编辑申请记录' : '添加求职申请'} onClose={() => setEditing(null)} wide><Form onCancel={() => setEditing(null)} onSubmit={form => { const record: Application = { id: editing.id ?? uid(), company: str(form, 'company'), position: str(form, 'position'), city: str(form, 'city'), noc: str(form, 'noc'), teer, date: str(form, 'date'), status: str(form, 'status') as Application['status'], custom: form.has('custom'), note: str(form, 'note') }; if (!record.company || !record.position) { setError('公司和职位不能为空。'); return; } setData(d => ({ ...d, applications: editing.id ? d.applications.map(a => a.id === record.id ? record : a) : [...d.applications, record] })); setEditing(null); notify('申请记录已保存'); }}><div className="form-grid"><Field label="公司"><input name="company" maxLength={200} required defaultValue={editing.company ?? ''} /></Field><Field label="职位"><input name="position" maxLength={200} required defaultValue={editing.position ?? ''} /></Field><Field label="城市"><input name="city" maxLength={100} defaultValue={editing.city ?? ''} /></Field><Field label="NOC 代码" hint="5 位数字；暂时不确定可留空"><input name="noc" inputMode="numeric" pattern="[0-9]{5}" maxLength={5} defaultValue={editing.noc ?? ''} placeholder="例如 21232" /></Field><Field label="TEER 等级"><select value={teer} onChange={e => setTeer(Number(e.target.value))}>{Array.from({ length: CONFIG.jobs.maxTeer + 1 }, (_, i) => <option key={i} value={i}>TEER {i}</option>)}</select></Field><Field label="投递日期"><input name="date" type="date" required max={today} defaultValue={editing.date ?? today} /></Field><Field label="当前状态"><select name="status" defaultValue={editing.status ?? 'applied'}>{JOB_STATUSES.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}</select></Field><label className="checkbox-field"><input type="checkbox" name="custom" defaultChecked={editing.custom ?? true} />这是一份定制申请</label>{teer > CONFIG.jobs.highestSkilledTeer && <div className="notice yellow full">这类工作不算技术类经验</div>}<div className="full"><Field label="备注"><textarea name="note" maxLength={2000} defaultValue={editing.note ?? ''} placeholder="招聘链接、面试安排、跟进事项……" /></Field></div></div>{error && <p className="form-error" role="alert">{error}</p>}</Form></Modal>}
    {employmentOpen && <Modal title="技术类工作入职日期" onClose={() => setEmploymentOpen(false)}><Form onCancel={() => setEmploymentOpen(false)} onSubmit={form => { setData(d => ({ ...d, settings: { ...d.settings, employmentDate: str(form, 'date') } })); setEmploymentOpen(false); notify('入职日期已保存'); }}><Field label="开始工作的日期" hint="留空表示尚未入职；修改日期会重新筛选可计入的工时。"><input type="date" name="date" defaultValue={data.settings.employmentDate} /></Field></Form></Modal>}
    {contactEditing && <Modal title={contactEditing.id ? '编辑联系记录' : '记录一次行业联系'} onClose={() => setContactEditing(null)}><Form onCancel={() => setContactEditing(null)} onSubmit={form => { const contact: Contact = { id: contactEditing.id ?? uid(), date: str(form, 'date'), name: str(form, 'name'), note: str(form, 'note') }; if (!contact.name) { setError('请输入联系人姓名。'); return; } setData(d => ({ ...d, contacts: contactEditing.id ? d.contacts.map(c => c.id === contact.id ? contact : c) : [...d.contacts, contact] })); setContactEditing(null); notify('联系已记录'); }}><div className="form-grid"><Field label="联系人姓名"><input required name="name" maxLength={100} defaultValue={contactEditing.name ?? ''} /></Field><Field label="联系日期"><input required name="date" type="date" max={today} defaultValue={contactEditing.date ?? today} /></Field><div className="full"><Field label="交流记录"><textarea name="note" maxLength={2000} defaultValue={contactEditing.note ?? ''} /></Field></div></div><p className="form-hint">同一周内相同姓名只计为一位联系人。</p>{error && <p className="form-error">{error}</p>}</Form></Modal>}
    {workEditing && <Modal title={workEditing.id ? '编辑每周工时' : '记录每周工时'} onClose={() => setWorkEditing(null)}><Form onCancel={() => setWorkEditing(null)} onSubmit={form => { const week = weekStart(str(form, 'week')); const log: WorkLog = { id: workEditing.id ?? uid(), week, hours: num(form, 'hours'), teer: num(form, 'teer'), eligible: form.has('eligible'), note: str(form, 'note') }; if (!data.settings.employmentDate || week < weekStart(data.settings.employmentDate) || week > today) { setError('请选择入职后且不晚于本周的日期。'); return; } if (data.workLogs.some(w => w.week === week && w.id !== log.id)) { setError('这周已有记录，请直接编辑该周，将多份工作工时合计填写。'); return; } setData(d => ({ ...d, workLogs: workEditing.id ? d.workLogs.map(l => l.id === log.id ? log : l) : [...d.workLogs, log] })); setWorkEditing(null); notify('每周工时已更新'); }}><div className="form-grid"><Field label="所在周的任意一天" hint="自动归入该周周一"><input type="date" name="week" required max={today} defaultValue={workEditing.week} /></Field><Field label="实际工时（小时）"><Amount name="hours" value={workEditing.hours ?? 0} max={CONFIG.validation.maxHours} step="0.25" /></Field><Field label="该周工作 TEER"><select name="teer" defaultValue={workEditing.teer ?? 0}>{Array.from({ length: CONFIG.jobs.maxTeer + 1 }, (_, i) => <option key={i} value={i}>TEER {i}</option>)}</select></Field><div className="full"><label className="checkbox-field"><input type="checkbox" name="eligible" defaultChecked={workEditing.eligible ?? false} /><span>确认这些是入职后、非全日制在读期间，在加拿大获授权从事的受雇有薪技术类工作工时。</span></label></div><div className="full"><Field label="备注"><input name="note" maxLength={1000} defaultValue={workEditing.note ?? ''} /></Field></div></div><p className="form-hint">本周只填已发生的工时。多份工作请合计符合条件的小时数，每周总计最多计入 {CONFIG.jobs.weeklyHourCap} 小时。</p>{error && <p className="form-error" role="alert">{error}</p>}</Form></Modal>}
  </>;
}
