import { useState } from 'react';
import { BookOpen, CalendarDays, Clock3, ExternalLink, Languages, Settings2 } from 'lucide-react';
import { CONFIG, SKILLS, STAGES } from './config';
import { usePlanner } from './context';
import { addDays, convertScore, currentStage, examStatus, inWeek, latestExam, levelLabel, number, overallLevel, shortDate, targetScore, uid, weekStart } from './lib';
import { AddButton, Amount, EditActions, Empty, Field, Form, Modal, num, Panel, Progress, str } from './components';
import type { Exam, Scores, Skill, StageId, StudyLog, TestKind } from './types';

export default function Language() {
  const { data, setData, today, notify } = usePlanner();
  const stage = currentStage(data, today);
  const [examEditing, setExamEditing] = useState<Partial<Exam> | null>(null);
  const [studyEditing, setStudyEditing] = useState<Partial<StudyLog> | null>(null);
  const [goalsOpen, setGoalsOpen] = useState(false);
  const [error, setError] = useState('');
  const hours = data.studyLogs.filter(l => inWeek(l.date, today)).reduce((sum, l) => sum + l.hours, 0);
  const goal = data.settings.weeklyStudyGoals[stage.id];
  const weeks = [...new Set([weekStart(today), ...data.studyLogs.map(l => weekStart(l.date))])].sort().reverse();
  const reminders = data.exams.filter(e => e.date <= today && examStatus(e, today).status !== 'valid').sort((a, b) => b.date.localeCompare(a.date));
  return <><div className="page-title"><div><div className="eyebrow">语言带来更多可能</div><h1>语言成长<span className="heading-dot">.</span></h1><p>英语稳步提升，法语持续积累。</p></div><AddButton onClick={() => setExamEditing({ kind: 'ielts', date: today })}>录入成绩</AddButton></div>
    {reminders.length > 0 && <div className="notice yellow"><CalendarDays size={19} /><div><strong>成绩有效期提醒</strong>{reminders.map(exam => { const status = examStatus(exam, today); return <p key={exam.id}>{exam.kind === 'ielts' ? 'IELTS General' : 'TEF Canada'} · {shortDate(exam.date)}：{status.status === 'expired' ? '已到期' : `还有 ${status.days} 天到期`}（{shortDate(status.expiry)}）。</p>; })}</div></div>}
    <div className="language-grid">{(['ielts', 'tef'] as const).map(kind => { const exam = latestExam(data, kind, today); const target = kind === 'ielts' ? CONFIG.language.englishTarget : CONFIG.language.frenchTarget; const prefix = kind === 'ielts' ? 'CLB' : 'NCLC'; const status = exam && examStatus(exam, today); return <Panel key={kind} title={kind === 'ielts' ? '英语 · IELTS General' : '法语 · TEF Canada'} action={<span className="badge green">目标 {prefix} {target}</span>}><div className="language-level"><span>{exam ? levelLabel(overallLevel(kind, exam.scores)) : '—'}</span><div><strong>{prefix}</strong><small>{exam ? '四项中的最低等级' : '还没有考试成绩'}</small></div><button className="text-button" onClick={() => setExamEditing({ kind, date: today })}>录入{kind === 'ielts' ? '雅思' : 'TEF'}成绩</button></div><div className="score-table"><div className="score-table-header"><span>单项</span><span>成绩 / 等级</span><span>距离目标</span></div>{SKILLS.map(skill => { const score = exam?.scores[skill.key]; const level = convertScore(kind, skill.key, score ?? null); const scoreGap = score === undefined ? null : Math.max(0, targetScore(kind, skill.key) - score); return <div className="score-table-row" key={skill.key}><span><i>{skill.short}</i>{skill.label}</span><span>{score ?? '—'}<small>{prefix} {levelLabel(level)}</small></span><span className={scoreGap === 0 ? 'positive' : 'muted'}>{scoreGap === null ? `需 ${targetScore(kind, skill.key)} 分` : scoreGap === 0 ? '已达标' : `还差 ${number(scoreGap)} 分`}{level !== null && level > 0 && level < target && <small>差 {target - level} 个等级</small>}</span></div>; })}</div><div className="exam-date-row"><CalendarDays size={14} /><span>{exam ? `${shortDate(exam.date)} 考试` : '考试日期待录入'}</span>{status && <span className={status.status === 'valid' ? 'muted' : 'danger-text'}>{shortDate(status.expiry)} 到期</span>}</div></Panel>; })}</div>
    <div className="source-note"><Languages size={17} /><p>TEF 请填成绩单上的 <strong>Équivalence ancien score</strong>，不是 Score / 699。等级 10 表示 10 及以上；低于 4 不再细分。<a href={CONFIG.links.language} target="_blank" rel="noreferrer">对照 IRCC 官网核实 <ExternalLink size={12} /></a></p></div>
    <div className="study-grid"><Panel title="本周法语学习" eyebrow="每周的小小积累" action={<button className="icon-button" aria-label="设置每周学习目标" onClick={() => setGoalsOpen(true)}><Settings2 size={17} /></button>}><div className="study-hours"><strong>{number(hours)}</strong><span>/ {goal} 小时</span><BookOpen size={35} strokeWidth={1.3} /></div><Progress value={hours} max={goal} label="本周法语学习目标" /><div className="flex-between study-caption"><span>{shortDate(weekStart(today))} — {shortDate(addDays(weekStart(today), 6))}</span><span>{hours >= goal ? '本周目标已完成' : `还差 ${number(goal - hours)} 小时`}</span></div><button className="button primary full-width" onClick={() => { setError(''); setStudyEditing({ date: today }); }}><Clock3 size={17} />记录学习时长</button><p className="small muted study-stage">当前为阶段 {stage.id} · {stage.name}</p></Panel><Panel title="每周汇总" action={<span className="small muted">周一开始 · 小时</span>}><div className="weekly-history">{weeks.slice(0, 8).map(week => { const total = data.studyLogs.filter(l => weekStart(l.date) === week && l.date <= today).reduce((sum, l) => sum + l.hours, 0); const weekStage = currentStage({ ...data, settings: { ...data.settings, stageOverride: null } }, week); const weekGoal = week === weekStart(today) ? goal : data.settings.weeklyStudyGoals[weekStage.id]; return <div className="week-history-row" key={week}><span>{week === weekStart(today) ? '本周' : shortDate(week).slice(2)}<small>{week === weekStart(today) ? shortDate(week) : `至 ${shortDate(addDays(week, 6))}`}</small></span><Progress value={total} max={weekGoal} label={`${week}学习汇总`} /><strong>{number(total)} <small>/ {weekGoal}</small></strong></div>; })}</div></Panel></div>
    <Panel title="学习日志" action={<span className="small muted">{data.studyLogs.length} 次记录</span>}>{data.studyLogs.length === 0 ? <Empty icon={<BookOpen size={28} />}>哪怕只有半小时，也值得记下来。</Empty> : <div className="table-scroll"><table><thead><tr><th>日期</th><th>时长</th><th>学习内容</th><th>操作</th></tr></thead><tbody>{[...data.studyLogs].sort((a, b) => b.date.localeCompare(a.date)).map(log => <tr key={log.id}><td>{shortDate(log.date)}</td><td>{number(log.hours)} 小时</td><td className="wrap-cell">{log.note || '—'}</td><td><EditActions name={`${log.date}学习`} onEdit={() => { setError(''); setStudyEditing(log); }} onDelete={() => { if (confirm('删除这条学习日志？')) setData(d => ({ ...d, studyLogs: d.studyLogs.filter(l => l.id !== log.id) })); }} /></td></tr>)}</tbody></table></div>}</Panel>
    <Panel title="考试记录" action={<span className="small muted">成绩有效期 {CONFIG.language.validYears} 年</span>}>{data.exams.length === 0 ? <Empty icon={<Languages size={28} />}>录入成绩后，考试日期与到期提醒会显示在这里。</Empty> : <div className="table-scroll"><table><thead><tr><th>考试 / 日期</th>{SKILLS.map(s => <th key={s.key}>{s.label}</th>)}<th>最低等级</th><th>有效期</th><th>操作</th></tr></thead><tbody>{[...data.exams].sort((a, b) => b.date.localeCompare(a.date)).map(exam => { const status = examStatus(exam, today); return <tr key={exam.id}><td>{exam.kind === 'ielts' ? 'IELTS G' : 'TEF Canada'}<small className="cell-note">{shortDate(exam.date)}</small></td>{SKILLS.map(s => <td key={s.key}>{exam.scores[s.key]}</td>)}<td>{exam.kind === 'ielts' ? 'CLB' : 'NCLC'} {levelLabel(overallLevel(exam.kind, exam.scores))}</td><td><span className={`badge ${status.status === 'valid' ? 'green' : status.status === 'soon' ? 'yellow' : 'red'}`}>{status.status === 'expired' ? '已到期' : status.status === 'soon' ? `${status.days} 天后到期` : '有效'}</span><small className="cell-note">{shortDate(status.expiry)}</small></td><td><EditActions name={`${exam.date}考试`} onEdit={() => setExamEditing(exam)} onDelete={() => { if (confirm('删除这次考试成绩？')) setData(d => ({ ...d, exams: d.exams.filter(e => e.id !== exam.id) })); }} /></td></tr>; })}</tbody></table></div>}</Panel>
    {examEditing && <ExamEditor exam={examEditing} close={() => setExamEditing(null)} />}
    {studyEditing && <Modal title={studyEditing.id ? '编辑学习记录' : '记录法语学习'} onClose={() => setStudyEditing(null)}><Form onCancel={() => setStudyEditing(null)} onSubmit={form => { const log: StudyLog = { id: studyEditing.id ?? uid(), date: str(form, 'date'), hours: num(form, 'hours'), note: str(form, 'note') }; const total = data.studyLogs.filter(l => l.date === log.date && l.id !== log.id).reduce((sum, l) => sum + l.hours, log.hours); if (total > CONFIG.validation.maxStudyDailyHours) { setError('一天的学习时长合计不能超过 24 小时。'); return; } setData(d => ({ ...d, studyLogs: studyEditing.id ? d.studyLogs.map(l => l.id === log.id ? log : l) : [...d.studyLogs, log] })); setStudyEditing(null); notify('学习已记录，这一小步也算数'); }}><div className="form-grid"><Field label="学习日期"><input type="date" name="date" required max={today} defaultValue={studyEditing.date} /></Field><Field label="学习时长（小时）"><Amount name="hours" min={0.25} max={CONFIG.validation.maxStudyDailyHours} step="0.25" value={studyEditing.hours ?? 1} /></Field><div className="full"><Field label="学习内容"><textarea name="note" maxLength={1000} defaultValue={studyEditing.note ?? ''} placeholder="例如：听力练习、口语课、复习词汇" /></Field></div></div>{error && <p className="form-error" role="alert">{error}</p>}</Form></Modal>}
    {goalsOpen && <Modal title="每周法语学习目标" onClose={() => setGoalsOpen(false)}><Form onCancel={() => setGoalsOpen(false)} onSubmit={form => { const goals = Object.fromEntries(STAGES.map(s => [s.id, num(form, `stage-${s.id}`)])) as Record<StageId, number>; setData(d => ({ ...d, settings: { ...d.settings, weeklyStudyGoals: goals } })); setGoalsOpen(false); notify('每周目标已更新'); }}><div className="form-grid">{STAGES.map(s => <Field key={s.id} label={`阶段 ${s.id} · ${s.name}（小时）`}><Amount name={`stage-${s.id}`} min={0.25} max={CONFIG.validation.maxHours} step="0.25" value={data.settings.weeklyStudyGoals[s.id]} /></Field>)}</div></Form></Modal>}
  </>;
}

function ExamEditor({ exam, close }: { exam: Partial<Exam>; close: () => void }) {
  const { data, setData, today, notify } = usePlanner();
  const [kind, setKind] = useState<TestKind>(exam.kind ?? 'ielts');
  const [values, setValues] = useState<Record<Skill, string>>({ listening: exam.scores ? String(exam.scores.listening) : '', reading: exam.scores ? String(exam.scores.reading) : '', writing: exam.scores ? String(exam.scores.writing) : '', speaking: exam.scores ? String(exam.scores.speaking) : '' });
  const [error, setError] = useState('');
  return <Modal title={exam.id ? '编辑考试成绩' : '录入考试成绩'} onClose={close} wide><Form onCancel={close} onSubmit={form => {
    const scores = Object.fromEntries(SKILLS.map(s => [s.key, Number(values[s.key])])) as Scores;
    if (SKILLS.some(s => !values[s.key] || convertScore(kind, s.key, scores[s.key]) === null)) { setError('请按所选考试的分数范围填写全部四项成绩。'); return; }
    const record: Exam = { id: exam.id ?? uid(), date: str(form, 'date'), kind, scores };
    if (data.exams.some(e => e.id !== record.id && e.kind === record.kind && e.date === record.date)) { setError('同一天同类型考试已存在，请编辑原成绩。'); return; }
    setData(d => ({ ...d, exams: exam.id ? d.exams.map(e => e.id === exam.id ? record : e) : [...d.exams, record] })); close(); notify('成绩已保存，等级已自动换算');
  }}><div className="form-grid"><Field label="考试类型"><select value={kind} onChange={e => { setKind(e.target.value as TestKind); setValues({ listening: '', reading: '', writing: '', speaking: '' }); }}><option value="ielts">IELTS General Training</option><option value="tef">TEF Canada · ancien score</option></select></Field><Field label="考试日期"><input type="date" name="date" max={today} required defaultValue={exam.date ?? today} /></Field></div>{kind === 'tef' && <p className="form-hint">请填写 Équivalence ancien score 栏：听力 /360、阅读 /300、写作和口语 /450。</p>}<div className="exam-score-grid">{SKILLS.map(s => { const score = values[s.key] === '' ? null : Number(values[s.key]); const level = convertScore(kind, s.key, score); return <div key={s.key}><Field label={`${s.label}分数`}><input type="number" min={0} max={CONFIG.language.maxScores[kind][s.key]} step={CONFIG.language.scoreSteps[kind]} required value={values[s.key]} onChange={e => setValues(v => ({ ...v, [s.key]: e.target.value }))} placeholder="—" /></Field><span className="score-preview">{kind === 'ielts' ? 'CLB' : 'NCLC'} {levelLabel(level)}</span><small className="muted">{score === null ? `目标 ${targetScore(kind, s.key)}` : score >= targetScore(kind, s.key) ? '已达到目标' : `还差 ${number(targetScore(kind, s.key) - score)} 分`}</small></div>; })}</div>{error && <p className="form-error" role="alert">{error}</p>}</Form></Modal>;
}
